### PR TITLE
FIX remove extra conditional statement in decision tree

### PR DESCRIPTION
**Pull request by PSSF23**

### CODE REVIEW

**Review by adam2392 — COMMENTED** [review]
Oh I see. This is used in UnsupervisedTree https://docs.neurodata.io/scikit-tree/dev/generated/sktree.tree.UnsupervisedDecisionTree.html

**Comment by PSSF23** [comment]
> Oh I see. This is used in UnsupervisedTree https://docs.neurodata.io/scikit-tree/dev/generated/sktree.tree.UnsupervisedDecisionTree.html

OK, the documentation says differently, so I didn't see it.

**Comment by adam2392** [comment]
> > Oh I see. This is used in UnsupervisedTree https://docs.neurodata.io/scikit-tree/dev/generated/sktree.tree.UnsupervisedDecisionTree.html
> 
> OK, the documentation says differently, so I didn't see it.

Ah I see. Feel free to update the PR to fix the documentation then.

**Comment by PSSF23** [comment]
@adam2392 why is `min_samples_split` calculation repeated in `super()._fit` and `_build_tree`? Shouldn't the local class handle it sufficiently?

**Comment by PSSF23** [comment]
I'll open another PR if other problems are found.

**Pull request closed without merging**
