### PR TITLE
FIX Adjust builder to support a different split record

### PR DESCRIPTION
**Pull request by thomasjpfan**
This is an example of how to get builder to work with the different types of split records.

This is functionally but I do not like the malloc + free in the builder.

All the setup.py `language="c++"` changes were needed to get the PR to compile on my machine

CC @adam2392

### CODE REVIEW

**Comment by thomasjpfan** [comment]
Er, still a segfault at the very end. I must have deleted too much code when I was cleaning up the diff.

**Comment by thomasjpfan** [comment]
The constraint on `SplitRecord` being a struct really constraints the trees. Also I may have broke something?

I do not have any more bandwidth to think about this for the next few weeks.

**Comment by thomasjpfan** [comment]
BTW I think there is a way to make this work with subclassing. We'll have to define a `cdef class _Record` that is returned by a Splitter. Interally, the splitter would use it's own struct to do splitting, but when the information is passed back up to the TreeBuilder, it will be in the `cdef class`.

It's very similar to how we do it in `HistGradientBoosting`:

https://github.com/scikit-learn/scikit-learn/blob/fb4dbfd837483ac3daf06dfc28871bfcfb65c4ab/sklearn/ensemble/_hist_gradient_boosting/splitting.pyx#L32

Note how there is a `split_info_struct` **and** a `SplitInfo` class and how their fields are very exactly the same.

**Comment by adam2392** [comment]
> BTW I think there is a way to make this work with subclassing. We'll have to define a `cdef class _Record` that is returned by a Splitter. Interally, the splitter would use it's own struct to do splitting, but when the information is passed back up to the TreeBuilder, it will be in the `cdef class`.
> One would need to experiment to see if this idea actually works.

Thanks for the info! I can work on it tomorrow.

Also, your idea of the malloc/free works! I fixed the bug it introduced to the algo and confirmed the performance is the same as before for both RF and OF. 

If the subclassing works, then I'll lyk and begin working on unit tests. Otw, I have a working commit in the draft PR using your idea. 

My colleague will also work on an in-depth example to append to the existing RF example.

**Comment by adam2392** [comment]
(Notes for myself) Main challenges I foresee:

- you can't use a Python class inside nogil. Remains to be seen if it's pure cdef, can we use inside nogil...
- might need an instantiated version within `TreeBuilder.build`

**Pull request closed without merging**
